apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
    - name: test-container
      image: busybox
      command: ["sh", "-c", "echo 'Hello, Kubernetes!' > /mnt/data/test.txt && sleep 3600"]
      volumeMounts:
        - mountPath: "/mnt/data"
          name: s3-volume
  volumes:
    - name: s3-volume
      persistentVolumeClaim:
        claimName: s3-pvc
        readOnly: false
