apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mysql-operator-role
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - persistentvolume
      - persistentvolumeclaims
      - deployments
    verbs:
      - get
      - list
      - watch
      - patch
      - create
      - update
      - delete
  - apiGroups:
      - otus.homework
    resources:
      - mysqls
    verbs:
      - get
      - list
      - watch
      - patch
      - create
      - update
      - delete
