apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-operator
  labels:
    app: mysql-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-operator
  template:
    metadata:
      labels:
        app: mysql-operator
    spec:
      serviceAccountName: mysql-operator-sa
      containers:
        - name: operator
          image: roflmaoinmysoul/mysql-operator:1.0.0
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: "/data"
              name: my-pvc
      volumes:
        - name: my-pvc
          persistentVolumeClaim:
            claimName: my-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
  labels:
    app: mysql-operator
spec:
  selector:
      app: mysql-operator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
  labels:
    app: mysql-operator
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
  labels:
    app: mysql-operator
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /mnt/data
