apiVersion: apps/v1
kind: Deployment
metadata:
  name: homework-deployment
  namespace: homework
spec:
  replicas: 3
  selector:
    matchLabels:
      app: homework-pod
  template:
    metadata:
      labels:
        app: homework-pod
    spec:
      nodeSelector:
        homework: "true"
      initContainers:
        - name: init-container
          image: busybox
          command: ['sh', '-c', 'wget -O /init/index.html https://google.com/index.html']
          #command: ['sh', '-c', 'echo "<html><body><h1>Homework Page</h1></body></html>" > /init/index.html']
          volumeMounts:
            - mountPath: /init
              name: shared-volume
      containers:
        - name: web-server
          image: nginx:latest
          ports:
            - containerPort: 8000
          volumeMounts:
            - mountPath: /homework
              name: shared-volume
          lifecycle:
            postStart:
              exec:
                command: ['rm', '/homework/index.html']
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - ls /homework/index.html
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: shared-volume
          emptyDir: {}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
