apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-exporter
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-exporter
  template:
    metadata:
      labels:
        app: nginx-exporter
    spec:
      containers:
        - name: exporter
          image: nginx/nginx-prometheus-exporter:1.4
          ports:
            - containerPort: 9113
              name: metrics
          args:
            - --nginx.scrape-uri=/metrics
