apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault-external-secret
spec:
  secretStoreRef:
    name: vault-secret-store
  target:
    name: vault-secret
    namespace: default
  data:
    - key: secret/otus
      name: credentials
