#repositories:
#  - name: bitnami
#    url: https://charts.bitnami.com/bitnami

releases:
  - name: kafka-prod
    chart: oci://registry-1.docker.io/bitnamicharts/kafka
    version: "31.3.1"
    namespace: prod
    createNamespace: true
    values:
      - "./releases/values/kafka-prod/kafka-prod-values.yaml"
  - name: kafka-dev
    chart: oci://registry-1.docker.io/bitnamicharts/kafka
    version: "31.3.1"
    namespace: dev
    createNamespace: true
    values:
      - "./releases/values/kafka-dev/kafka-dev-values.yaml"
