#repositories:
#  - name: bitnami
#    url: https://charts.bitnami.com/bitnami

releases:
  - name: kafka-prod
    chart: oci://registry-1.docker.io/bitnamicharts/kafka
    version: "31.3.1"
    namespace: prod
    createNamespace: true
    values:
      - "./values/kafka-prod-values.yaml"
#  - name: kafka-dev
#    chart: bitnami/kafka
#    namespace: dev
#    createNamespace: true
#    values:
#      replicaCount: 1
#      replicas: "1"
#      authentication:
#        method: none
#      listeners:
#        type: PLAINTEXT
